### ISSUE TITLE
[11] Password expiration cannot be disabled

### ISSUE THREAD

**Issue by javiermatos** [OCA/server-auth#100]
I have noticed password_security/models/res_users.py is different for versions 11 and 12 regarding the _password_has_expired function: in version 12, there is a condition that allows to disable password expiration just by setting password_expiration = 0 (which makes sense),

```
    @api.multi
    def _password_has_expired(self):
        self.ensure_one()
        if not self.password_write_date:
            return True

        if not self.company_id.password_expiration:
            return False

        days = (fields.Datetime.now() - self.password_write_date).days
        return days > self.company_id.password_expiration
```

while in version 11, the function does not accept a value just to disable it.

```
    @api.multi
    def _password_has_expired(self):
        self.ensure_one()
        if not self.password_write_date:
            return True
        write_date = fields.Datetime.from_string(self.password_write_date)
        today = fields.Datetime.from_string(fields.Datetime.now())
        days = (today - write_date).days
        return days > self.company_id.password_expiration
```

Can we "backport" that feature or is there any reason not to implement it that way in version 11? Will you accept a pull request of that feature to be merged in 11.0 branch?

**Comment by pedrobaeza** [comment]
Please do the proper PR with the backport.

**Comment by javiermatos** [comment]
Hola Pedro, I think the PR is done and ready to merge. Please, tell me in case there is something else I have to fix/improve for having this ready.

**Comment by pedrobaeza** [comment]
OK, closing this one as there's a PR. Have you signed CLA?
