### ISSUE TITLE
[IDEA] password_security: Using zxcvbn python library

### ISSUE THREAD

**Issue by moylop260** [OCA/server-auth#111]
Currently the module [password_security](https://github.com/OCA/server-auth/tree/96989f94c68fe52ca6768a6787968e140e205058/password_security) is using a similar case to:

Unsafe password is passed as safe:
 - ![Screen Shot 2019-06-07 at 11 38 57 AM](https://user-images.githubusercontent.com/6644187/59120015-efb03100-8919-11e9-903c-ac43cedc4611.png)

Safe password is passed as unsafe:
 - ![Screen Shot 2019-06-07 at 11 38 51 AM](https://user-images.githubusercontent.com/6644187/59120016-f048c780-8919-11e9-951a-4a11a6012dab.png)

The following python library:
 - https://pypi.org/project/zxcvbn/

Works a little different similar to:
 - ![image](https://user-images.githubusercontent.com/6644187/59120276-9bf21780-891a-11e9-84fb-c52e9ae7845c.png)

And gives you a score of security of your password considering the name of the user too.
I mean, `name = John Smith` and `password = JhonSmith123` it is unsafe.

For more information check the following readme:
 - https://github.com/dwolfhub/zxcvbn-python/blob/master/README.rst

Note: Help wanted here.

**Comment by moylop260** [comment]
FYI Django has implemented this way too:
  - https://pypi.org/project/django-zxcvbn-password/

    - ![django](https://user-images.githubusercontent.com/6644187/59121903-ee353780-891e-11e9-836a-732d2e1a7f3b.png)

**Comment by pedrobaeza** [comment]
Isn't Odoo already doing something similar in v12?

**Comment by fkantelberg** [comment]
This goes beyond the scoring in auth_password_policy because of the dictionaries. I think this would be a nice feature for the mentioned module and I would work on it.

**Comment by moylop260** [comment]
Hi @fkantelberg 
Your help is welcome!
Thanks!

**Comment by fkantelberg** [comment]
@moylop260 
This PR #130 should implement it.

I'm currently not quite sure because it uses the js and python lib for zxcvbn which could result in different scores in the future if not both are updated. But this way will limit the requests to odoo which would be required per change of the password field.

What do you think?
