### ISSUE TITLE
[11.0] password_security - redirection fails when password expired and website installed

### ISSUE THREAD

**Issue by Martronic-SA** [OCA/server-auth#119]
It seems that sometimes the method in the website module controllers/main.py web_login is overriding the one in password_security and then if the password has expired, user is not redirected on the signup_url but on the standard /web page and therefore cannot login anymore.
How to be sure that password_security is on the top? should it be added to the server_wide_modules in conf? (it seems that it doesn't help..)

**Comment by amkarthik** [comment]
@Martronic-SA 
Please review https://github.com/OCA/server-auth/pull/124.
It will fix this issue.
