### ISSUE TITLE
Getting "--HACK--" Message on auth_signup_verify_email 

### ISSUE THREAD

**Issue by juhenriquez** [OCA/server-auth#146]
Running into an issue with auth_signup once tried to login I get “--HACK--’’ on signup Screen

![img111](https://user-images.githubusercontent.com/8250019/69423052-8ff8e700-0cfb-11ea-993e-fa2fd3a2c9e6.jpg)

Was able to reach this point, 
![pciter12](https://user-images.githubusercontent.com/8250019/69423076-9edf9980-0cfb-11ea-93c2-4229cbc58d56.jpg)

But not really sure what is happening here.

Working on Odoo v12e.

**Comment by pedrobaeza** [comment]
Screenshots too small, but any way, see #145 that removes the hack.
