### ISSUE TITLE
Keycloak login only works first time

### ISSUE THREAD

**Issue by clayrisser** [OCA/server-auth#150]
I am using keycloak v8.0.1 and odoo v11. After setting up the keycloak integration, everything works great, however, when I log out of odoo and try to log in again, I get a 502 error from keycloak.

One thing I did notice is the `redirect_uri` contains the `http` protocol instead of the `https` protocol, even though all of my config says to use `https`. I would blame it on my configuration setup, except that it really does work the first time I login.

![Screenshot from 2019-12-11 10-51-40](https://user-images.githubusercontent.com/6234038/70642479-e3789980-1c04-11ea-81a6-882e5875670b.png)

```
https://iam.siliconhills.dev/auth/realms/master/protocol/openid-connect/auth?client_id=hq.siliconhills.dev&redirect_uri=http%3A%2F%2Fhq.siliconhills.dev%2Fauth_oauth%2Fsignin&response_type=token&state=%7B%22r%22%3A+%22http%253A%252F%252Fhq.siliconhills.dev%252Fweb%22%2C+%22d%22%3A+%22hq-siliconhills-dev%22%2C+%22p%22%3A+7%7D&scope=False
```

In order to make it work, I have to logout of keycloak, and then try to login to odoo with keycloak. But, if I'm already logged into keycloak and I try to login to odoo with keycloak, it always throws a `502` error.

Below is my configuration.

![Screenshot from 2019-12-11 10-54-30](https://user-images.githubusercontent.com/6234038/70642425-ce036f80-1c04-11ea-9e44-31d3f0d92ac1.png)
![Screenshot from 2019-12-11 10-55-44](https://user-images.githubusercontent.com/6234038/70642434-cfcd3300-1c04-11ea-8c90-352af4ecc367.png)

Neither keycloak or odoo give me any error logs. Keycloak only logs the following warnings.

![Screenshot from 2019-12-11 10-57-28](https://user-images.githubusercontent.com/6234038/70642591-1589fb80-1c05-11ea-8b37-6c5cc135a3cf.png)

**Comment by raphaelsoul** [comment]
in my case i cannot login admin console again. but works again after cleaned cookies on keycloak.

**Comment by clayrisser** [comment]
I got past this issue, but I don't remember how.
