### ISSUE TITLE
New modules about "res.users.log"

### ISSUE THREAD

**Issue by yelizariev** [OCA/server-auth#154]
I need a way to show records of ``res.users.log`` model. Odoo doesn't provide views for the model and I haven't found a ready solution for that. So, I think to create the module.

My question is: what could be a proper name / technical name for such a module and is ``server-auth``  proper repository for it?

**Comment by pedrobaeza** [comment]
Well, good question, as there's no good host to it being something transversal, but I would bet for this one as the more related one (excluding server-tools, that it's the wildcard one).

About the name...

![image](https://user-images.githubusercontent.com/7165771/71356000-23cf0480-2581-11ea-82c1-dccca7660404.png)

:rofl: 

Seriously, I think you can name it as `user_log_view`.
