### ISSUE TITLE
auth_from_http_remote_users: allow multiple sessions for same user

### ISSUE THREAD

**Issue by sbidoul** [OCA/server-auth#170]
Currently, `auth_from_http_remote_users` does not allow the same user to connect from different browser sessions at the same time (different browsers, different machines etc).

This is due to the fact that, when creating a new session, the module [generates a new random pseudo-password (sso_key)
](https://github.com/OCA/server-auth/blob/582433d21b73e0c0710dbea5bab8ffa9223fd60c/auth_from_http_remote_user/controllers/main.py#L48-L49) that is subsequently used to [check credentials](https://github.com/OCA/server-auth/blob/582433d21b73e0c0710dbea5bab8ffa9223fd60c/auth_from_http_remote_user/models/res_users.py#L19-L24) at the beginning of each request (via `check_security`). So when the same user tries to connect via two sessions, they invalidate each other.

While there are reasons to make this `sso_key` secret, there is no reason for it to be random, IMO.

So I propose to change the module to generate that `sso_key` by hashing the combination of the user id, and a per-database secret to be set in a system parameter. For compatibility, if the system parameter is absent, log a warning and fall back on the current mechanism.

**Comment by sbidoul** [comment]
@lmignon

**Comment by lmignon** [comment]
@sbidoul  all this makes sens

**Comment by apineux** [comment]
FYI after trying to migrate this module to version 13.0. I realize that Odoo doesn't use the check_credentials method at the beginning of each request. It uses it once at the session creation but after that, the credentials are not checked anymore.
Therefore we can keep the current behavior in version 13.0 as it already allow multiple connection from different browser sessions.

**Comment by dannyadair** [comment]
> FYI after trying to migrate this module to version 13.0. I realize that Odoo doesn't use the check_credentials method at the beginning of each request. It uses it once at the session creation but after that, the credentials are not checked anymore.
> Therefore we can keep the current behavior in version 13.0 as it already allow multiple connection from different browser sessions.

So in v13 there is no need for `sso_key` at all?
