### ISSUE TITLE
MS ADFS Integration?

### ISSUE THREAD

**Issue by ansersolutions** [OCA/server-auth#193]
Hello all,
Has anyone managed to setup the SAML connector with Microsoft ADFS SSO?

If so.. what should I place in each of the SAMLv2 setup screen?

Kind regards,

Fernando

**Comment by ahilalix** [comment]
@cocinfar 

Have you found a solution?.

Thanks.

**Comment by ansersolutions** [comment]
No... not yet... :/

**Comment by olivier-theatre** [comment]
Hi everyone,

Does someone know if Microsoft ADFS SSO is working with latest version of server-auth and SAML ?

Best regards,

Olivier
