### ISSUE TITLE
v12 Lasso requirement issue

### ISSUE THREAD

**Issue by flotho** [OCA/server-auth#195]
Hi @gurneyalex and @Yajo 

I have some issue to install lasso on centos8 through ansible and it looks like there's a problem with versions used.

The official reference of the lasso https://pypi.org/project/lasso/ is precising that it's an alpha stage and moreover when you follow the doc and you want to point to the https://github.com/aperezdc/lasso-python it has been renamed in gnarl
My proposal is to user lasso-python instead of the actual dependency or to find a more "stable" dependency .
What's your point of view ?

Regards

**Comment by yajo** [comment]
What module are we talking about?

**Comment by flotho** [comment]
actually, the requirements.txt of this repo is responsible of this possible bad dependency.
SAML seems to be affected.

**Comment by yajo** [comment]
I'm not of the most active users of that module. Probably @gurneyalex or @max3903 can tell you better.

**Comment by 101t** [comment]
I made this tutorial 
how to install `lasso` the C library with `auth_saml`
https://github.com/101t/install-lasso-saml2

**Comment by shalinwilson** [comment]
I am getting an error like lasso doesnt have server. auth_saml.py line 50
server = lasso.Server.newFromBuffers(

**Comment by gurneyalex** [comment]
the last version of auth_saml has dropped that requirement.
