### ISSUE TITLE
[12] auth_session_timeout forces website redirect

### ISSUE THREAD

**Issue by Moto017** [OCA/server-auth#208]
Forces website homepage redirect to /web/login
Duplicated issue with runbot

Steps to reproduce

1. install website
2. install additional website
3. in new browser / incognito, go to homepage
4. redirected from home page to /web/login?redirect=http%3A%2F%2F3428879-12-0-2bfb2b.runbot1-2.odoo-community.org%2F

**Comment by JDSalcedo** [comment]
Maybe this comment could solve your problem:
https://github.com/OCA/server-auth/issues/216#issuecomment-729166966
