### ISSUE TITLE
[12.0][auth_session_timeout] "414 Request-URI too large" Error

### ISSUE THREAD

**Issue by Danoolo** [OCA/server-auth#216]
Hi guys!, i'm getting this "414 Request-URI too large" Http error when use auth_session_timeout module in my server with a Nginx proxy in front of it...i figured out that this module generate redirection when it try to validate the session and that redirection uri gets too large to process. That error become rude because public users cant access to my odoo webpage because of session timeout..and it is neither an option to uninstall the module because i need session timeouts.
My question is that's a problem in that OCA module or maybe some bad configuration?. Thanks so much and i hope this issue is ok here!.

**Comment by jusle** [comment]
I have the same error on Odoo 12.0 with nginx and Python 3.7, and confirmed it is because of this module. 

This is what I see on logs:

```
2020-10-21 12:48:54,242 5257 ERROR dbname odoo.addons.auth_session_timeout.models.res_users: Exception reading session file modified time.
Traceback (most recent call last):
  File "/opt/odoo/addons/foss/server-auth/auth_session_timeout/models/res_users.py", line 74, in _auth_timeout_check
    expired = getmtime(path) < deadline
  File "/usr/lib/python3.7/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/opt/odoo/.local/share/Odoo/sessions/werkzeug_d9cb4c19088fb00b5c508b4e174bdd856f9f508d.sess'
```

It is making some kind of redirection loop. For public user without authentication (cookies cleared) it ends up to the login page (/web/login).

**Comment by shabeervpk** [comment]
If we put **/web/login** to **inactive_session_time_out_ignored_url** does it resolves the problem !!!
