### ISSUE TITLE
Error on installing email_verification

### ISSUE THREAD

**Issue by joanbruch** [OCA/server-auth#219]
Hi, 
I've download the .zip and moved the extracted folder to the addons folder of Odoo V13 Enterprise. 
Also I've installed pip3 install email_validator 

![image](https://user-images.githubusercontent.com/37068744/94660307-cc2aaa00-0305-11eb-8a1f-85ae7c2f94a3.png)

but when I try to install the module on Odoo, it appears the error: 
![image](https://user-images.githubusercontent.com/37068744/94660132-95549400-0305-11eb-81e6-d03d4b6dca38.png)

Please, can anyone help me with that error? 
Thank you in advance, 
Joan

**Comment by pedrobaeza** [comment]
That's because the Odoo Python environment is not the same as the pip3 Python environment.

Closing as no module issue, but deployment one.

**Comment by pedrobaeza** [comment]
Other option is that you haven't restarted Odoo service after installing the Python library.

**Comment by joanbruch** [comment]
Yes, i've restarted Odoo service after installing the Python library, but the error persists. 
And also I have the Odoo service and the Python pip3 in the same server environment.

**Comment by pedrobaeza** [comment]
I'm afraid you don't. If not, the error wouldn't arise. You can try in runbot link to see that is working. If not, then comment back.
