### ISSUE TITLE
How to install lasso module

### ISSUE THREAD

**Issue by shyjuk** [OCA/server-auth#24]
module: auth_saml
version: 11.0

**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**

**Comment by pedrobaeza** [comment]
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Comment by shyjuk** [comment]
I have installed lasso with command  apt install python-lasso
import lasso also works from the python command line.
But still the module complaints "No module named lasso"

**Comment by phong-innomizetech** [comment]
@shyjuk Did you find out the root cause?

**Comment by smurf-U** [comment]
Any update? @shyjuk
