### ISSUE TITLE
[14.0] auth_session_timeout: expiration checking

### ISSUE THREAD

**Issue by alexeirivera87** [OCA/server-auth#259]
https://github.com/OCA/server-auth/blob/ceed639b21f2ce07685accb1f06de2b91d29b9be/auth_session_timeout/models/res_users.py#L73

Hello,
it is working the expiration checking? I set the system parameter to 120 seconds, and after that time the user session is not terminated. Am I missing a detail?

**Comment by lonelyleaves** [comment]
me too ,this model not work!

**Comment by sunarctech** [comment]
Me too, this model not work!

While debugging code
1) https://github.com/OCA/server-auth/blob/ceed639b21f2ce07685accb1f06de2b91d29b9be/auth_session_timeout/models/res_users.py#L37
Comments/Issue: To calculate deadline time the above formula used, is logic correct? Please confirm

2) https://github.com/OCA/server-auth/blob/ceed639b21f2ce07685accb1f06de2b91d29b9be/auth_session_timeout/models/res_users.py#L73
Comments/Issue: getmtime(path) time is always greater that deadline.  (So never expired is True always showing False)

3) https://github.com/OCA/server-auth/blob/ceed639b21f2ce07685accb1f06de2b91d29b9be/auth_session_timeout/models/res_users.py#L51
Comments/Issue: if manually called this function session.uid always showing None, so session logout code never called  
https://github.com/OCA/server-auth/blob/ceed639b21f2ce07685accb1f06de2b91d29b9be/auth_session_timeout/models/res_users.py#L52

Please confirm the above issue and provide the fix solutions.

**Comment by prakashjain** [comment]
Me too, this model not work!

While debugging code
1) https://github.com/OCA/server-auth/blob/ceed639b21f2ce07685accb1f06de2b91d29b9be/auth_session_timeout/models/res_users.py#L37
Comments/Issue: To calculate deadline time the above formula used, is logic correct? Please confirm

2) https://github.com/OCA/server-auth/blob/ceed639b21f2ce07685accb1f06de2b91d29b9be/auth_session_timeout/models/res_users.py#L73
Comments/Issue: getmtime(path) time is always greater that deadline.  (So never expired is True always showing False)

3) https://github.com/OCA/server-auth/blob/ceed639b21f2ce07685accb1f06de2b91d29b9be/auth_session_timeout/models/res_users.py#L51
Comments/Issue: if manually called this function session.uid always showing None, so session logout code never called  
https://github.com/OCA/server-auth/blob/ceed639b21f2ce07685accb1f06de2b91d29b9be/auth_session_timeout/models/res_users.py#L52

Please confirm the above issue and provide the fix solutions.

Edit: **It seems getmtime(path)  Get modify time  session path  always showing current time (utc) after odoo idle** 
Any updated on the issue? Please fix

**Comment by prakashjain** [comment]
Please reply any solutions regarding the above issue?

**Comment by prakashjain** [comment]
auth_session_timeout version 14 tested not working, Testing purpose 2 or 5 minutes set.
Issue opened more than 2 months, but no reply.
Please let me know how to fix the above issue.

**Comment by lonelyleaves** [comment]
auth_session_timeout v14 is not work, inactive_session_time_out_delay is 600，but  opened more than 10min ,it‘s no reply.

**Comment by thomaspaulb** [comment]
Fixed in https://github.com/OCA/server-auth/pull/535
