### ISSUE TITLE
[14.0] password_security: Invalid signup token (after validation message)

### ISSUE THREAD

**Issue by prakashjain** [OCA/server-auth#264]
Below steps to reproduce the Invalid signup token

1) Send Password Reset Instructions to the user
2) User immediately try to reset password with old password system through validation message
**Cannot use the most recent passwords**
3) Then user try to set new password but this time showing "Invalid signup token"  
Expected  Behaviour: User able to login with new password

Note: Using password reset link use try to reset passwords within 24 hours and  only one time try to reset password but failed.

Similar Issue: https://github.com/OCA/server-auth/issues/54

**Comment by LJared** [comment]
Hello @prakashjain. Were you able to fix this bug by yourself? Or did you get any support?

**Comment by evaldez89** [comment]
Hey @LJared, (I'm @evaldezb that was my old account comming from issue #54) still having the same situation, odoo 11 and 12. No idea why it keeps changing the token.

I think you provided very helpful details on #54. Tell me something, can you replicate the behaivior every time just by manually forcing the password to expire and trying to access with the correct password? or do you think something else is involved?

**Comment by elymaralfaroxmarts** [comment]
Hi. Is there any solution? In odoo v15  this is still happening. I sent the reset password email , and when you click on it the token on the partner-user changes. Why?
