### ISSUE TITLE
auth_api_key: License conflict

### ISSUE THREAD

**Issue by dreispt** [OCA/server-auth#273]
auth_api_key: The license LGPL-3 conflicts with one of its dependencies. Please make sure that you comply with the licenses compatibility. See our FAQ at https://apps.odoo.com/apps/faq#maintainer_faq_04 .

**Comment by simahawk** [comment]
@lmignon @sebastienbeau could you check this?

**Comment by lmignon** [comment]
Thank you for the issue. We have to check if it's possible to re license server_environment.

**Comment by simahawk** [comment]
https://github.com/OCA/server-env/pull/77 CC @guewen

**Comment by dreispt** [comment]
I work around could be to move the `server_environment` to  a glue module.
And IMO you don't really need `server_environment` to implement API Key support.

**Comment by simahawk** [comment]
OCA/server-env#77 is getting merged. I agree w/ @dreispt that api key could be decoupled from server env. @lmignon what do you think?

**Comment by lmignon** [comment]
@simahawk @dreispt indeed api key could be decoupled from server env. I will be happy to review any PR on this topic

**Comment by simahawk** [comment]
this is solved and server env was decoupled on https://github.com/OCA/server-auth/pull/288
