### ISSUE TITLE
 redirect = werkzeug.utils.redirect(auth_request, 303)

### ISSUE THREAD

**Issue by ogba** [OCA/server-auth#279]
Hello , how can redirect  to url throw proxy   

redirect = werkzeug.utils.redirect(auth_request, 303)

need to assess to auth_request url throw proxy

**Comment by pedrobaeza** [comment]
This is a question, not an issue, and not directly related with the modules in this repository, so closing. Post the question in the forums.

**Comment by ogba** [comment]
@pedrobaeza  thanks a lot ,  please can you give me the forum link

**Comment by pedrobaeza** [comment]
Sorry, I don't know about this part, and if you expect to have answers, you should elaborate more your question: http://www.catb.org/~esr/faqs/smart-questions.html
