### ISSUE TITLE
errors with odoo 10

### ISSUE THREAD

**Issue by makayabou** [OCA/server-auth#289]
Hello, 
I'm trying to use your  plugin  auth_keycloak 10.0.1.1.0 with Odoo 10.0-20190816 (Community Edition)  and Keycloak 15.0.2.

After installing and setting keycloak client and odoo plugin, I get the following error:
![error2](https://user-images.githubusercontent.com/25554584/134779819-1391c690-c786-469b-b734-1e12c66616dd.png)

I use a temporary workaround for this: 
![auth_keycloak_settings](https://user-images.githubusercontent.com/25554584/134779850-98bb00e6-ba46-48ce-9013-aa19e26897ab.png)

Now I am redirected to keycloak login page, but after auth i'm redirected to odoo login page with an auth_error=3:
![error3](https://user-images.githubusercontent.com/25554584/134779856-e3e6988c-4e7a-4a46-b68e-5da94bc77fcd.png)

Would someone have tips ?

Thanks

**Comment by deepa4lok** [comment]
I too had this issue & made it work with some fix, will shortly send PR, however in the meantime if you try changing scope as 'profile' & see if that works for you.
