### ISSUE TITLE
v14 auth_saml:  I am missing the requirement for Python library not installed: pysaml2 in auth_saml

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [OCA/server-auth#295]
Hi
I get this error when I install auth_saml
`Python library not installed: pysaml2`

I think this can be solved by adding a requirement to install it in the manifest, but I do not know how to do it.

make a suggestion in the error message to run: 
pip install pysaml2

Thanks
/Fredrik

**Comment by fredrikarvas-vertel** [comment]
I found this comment: 
https://www.odoo.com/forum/help-1/how-to-automatically-install-an-external-python-library-along-with-the-installation-of-your-custom-module-161760

and understand now that there is a note in the manifest about the requirement.
https://github.com/OCA/server-auth/blob/68c7b289ffb8db6ef5442bf8d02a69b6deff1464/auth_saml/__manifest__.py#L13

Is there a way to automatically install it when installing the module?

**Comment by theangryangel** [comment]
The error message which looks at is from [core Odoo](https://github.com/odoo/odoo/blob/9d6f54e7f7219cbbda41129e35682f6a76aae1d4/odoo/addons/base/models/ir_module.py#L338). 

With regards to automatically installing it there's no guarantee that the user account that Odoo runs as can install any python modules, nor that it can reach pypi to install it. This is the reason why the external_dependencies exists in the manifest. This is the responsibility of the sysadmin managing the Odoo installation.

**Comment by oussjarrousse** [comment]
What if I am using the odoo docker image with docker-compose. Would the "external_dependencies": {"python": ["pysaml2"]}, be enough? especially if for some reason i decided to docker-compose rm the odoo container.

My solution was to create a custom Dockerfile that looks like this:
```
FROM odoo:14.0
USER root
RUN apt-get update
RUN apt-get install python3-pysaml2 -y
USER odoo
```
