### ISSUE TITLE
Please copy the auth_signup_verify_email to the v14-repo

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [OCA/server-auth#296]
Hi 
we have tested the auth_signup_verify_email-module in v14 CE. 
It worked fine. 
Please copy the module to the v14 repo (and update the major-version number to 14.0.).

Sincererly
Fredrik

**Comment by pedrobaeza** [comment]
There's an opened pull request for it: https://github.com/OCA/server-auth/pull/270

Please review it.

**Comment by fredrikarvas-vertel** [comment]
Thanks @pedrobaeza 
I am learning!

**Comment by pedrobaeza** [comment]
https://odoo-community.org/page/review
