### ISSUE TITLE
14.0 Vault - error when creating a new entry from the "Entry"-meny.

### ISSUE THREAD

**Issue by fredrikarvas-vertel** [OCA/server-auth#297]
Testcase: 
Logged in user, with key-file. I can create entires if I start from the vault and pick the smart button "Entries". 

I get this message after I click on: Vault -> Entries -> Create.

![image](https://user-images.githubusercontent.com/61729317/136326356-2a7f50bf-c56d-4836-b0ea-f375f95c98fc.png)

Suggestions (ideas how to solve it): 
- Add a link to a vault for the new entry
- Add default values for the missing fields
- Please change the error message to: Please create new entries by starting from the current vault.
- Remove the "create button" when the user comes directly to the Entries

I can as one of our developers to do this if it is the right thing to do, but I am new in contributing, so I want to do it the right way.

Sincererly
Fredrik

**Comment by fkantelberg** [comment]
This should be one of the fixes in #302
