### ISSUE TITLE
Keycloak signin: Migration to 14.0/15.0?

### ISSUE THREAD

**Issue by valentinthirion** [OCA/server-auth#301]
Hello,
I'm wondering if there is any chance or work in progress to migrate to the last versions od Odoo the module that allows to sign into Odoo using Keycloak, that is available only for Odoo 11.0?

Best regards

**Comment by sbidoul** [comment]
@valentinthirion look at `auth_oidc` which implements standard based OpenId Connect authentication, which is fully supported and confirmed to work with keycloak. See also https://github.com/OCA/server-auth/pull/261#issuecomment-819448516 about the other part of `auth_keycloak`.

**Comment by valentinthirion** [comment]
Thanks Stephan!
