### ISSUE TITLE
Got 500 internal server error auth_saml/get_auth_request  

### ISSUE THREAD

**Issue by ranjith244** [OCA/server-auth#345]
<!-- Provide a general summary of the issue in the Title above.
Issue in creating saml provider in my odoo 13

I have added the followed details in SAML provider

![saml_issue](https://user-images.githubusercontent.com/42739929/155139732-778b2bfa-f997-478d-b1fe-0925366420e9.png)
 
I am not able to login once i added all the details for SAML provider

I got this error

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

When i checked my logs i found below error
![saml_login_issue](https://user-images.githubusercontent.com/42739929/155140384-0061cb2a-d394-4711-b3d4-312045cee863.png)

**Comment by westley333** [comment]
generate keys on your local machine and upload them in the saml provider settings in odoo

example on local machine:
openssl req -x509 -newkey rsa:4096 -keyout odoo-key.pem -out odoo-cert.pem -sha256 -days 3650 -nodes
