### ISSUE TITLE
auth_from_jwt

### ISSUE THREAD

**Issue by ayushin** [OCA/server-auth#408]
Hi,

Now that there is `auth_jwt` and `auth_from_remote_user` I wonder why there is not `auth_from_jwt` that would create a session and sign user in?

I guess I miss something architecture wise? @sbidoul

**Comment by sbidoul** [comment]
@ayushin `auth_jwt` has a [user_id_strategy](https://github.com/OCA/server-auth/blob/d75b6f7dfa39a9e967b2d68b857ea89a8387c768/auth_jwt/models/auth_jwt_validator.py#L161-L164) that is meant to be extended.

If you need a full Odoo sign in, you may also be interested in `auth_oidc` for an OpenId Connect implementation.

**Comment by ayushin** [comment]
I saw that thank you! What I need is to sign in user by url redirect from another backend where the user is already authorised  without the user knowing it is being signed in again.

I am not an expert with Openid but I believe the flow has to be initiated by the user and there will be some auth screens in between?

For now what I have in mind is to direct user with JWT header pre-set by another backend to some jwt endpoint that would do what auth/session does and redirect it to the final url.

Not sure how user_id_strategy helps me with that? @sbidoul
