### ISSUE TITLE
[13.0] vault: Loosing keys when changing vault on an entry

### ISSUE THREAD

**Issue by CarlosRoca13** [OCA/server-auth#423]
TT38963

In module vault (at least in v13), when we change an entry from one vault to another existing vault, the values added on this entry cannot be accessed.

I'm not sure if this change should be allowed, if not, we should make the field readonly when it is defined to avoid this errors.

What do you think? @pedrobaeza @fkantelberg

**Comment by pedrobaeza** [comment]
I think that this field should be readonly if the entry is already created.

**Comment by fkantelberg** [comment]
Readonly would be the best otherwise it's getting complicate again. If you want to move entries between vaults you can use the export -> import quite well.

**Comment by pedrobaeza** [comment]
Let's go with that approach then. We can notice such thing in the known issues section and suggest Export/Import alternative. @CarlosRoca13 can you do the PR?

**Comment by pedrobaeza** [comment]
@CarlosRoca13 was this done?

**Comment by CarlosRoca13** [comment]
No, sorry, I had lost the notification between mails... :sweat_smile: 

I will do the change right now
