### ISSUE TITLE
Unable to install module "password_security" because an external dependency is not met: Python library not installed: zxcvbn

### ISSUE THREAD

**Issue by SAMSA-IT** [OCA/server-auth#435]
## Module
The name of the module that has a bug:
password_security

## Describe the bug
When installing the app the following error is shown:
Unable to install module "password_security" because an external dependency is not met: Python library not installed: zxcvbn
![grafik](https://user-images.githubusercontent.com/24456505/198326534-27c0052f-073b-42ef-9639-67e865bd3079.png)

## To Reproduce
**Affected versions**: V14

1. Install app password_security

**Expected behavior**
There should be no error or there should be a description on how to incorporate the missing library.

**Comment by pedrobaeza** [comment]
You should have such library in your Odoo Python environment. It's not a problem of the module itself, but your deployment.

**Comment by SAMSA-IT** [comment]
Hello Pedro,
thank you for the quick info.
We use Odoo.sh. Can we use the module on Odoo.sh?
Best regards,
Manuel

**Comment by pedrobaeza** [comment]
I don't know such platform, but I suppose there's a place where you can put extra Python libraries. Ask where this can be done to SH support.

**Comment by SAMSA-IT** [comment]
Thanks Pedro! I will do it.

**Comment by SAMSA-IT** [comment]
Dear Pedro,
Odoo replied that a requirements.txt file listing the external libraries is required for the app to run on Odoo.sh.
The platform Odoo.sh will use this file to automatically install the Python libraries your project needs.
https://www.odoo.com/documentation/14.0/administration/odoo_sh/getting_started/first_module.html#use-an-external-python-library

Do you think this requirements.txt file could be added to the app?
Best regards,
Manuel

**Comment by pedrobaeza** [comment]
The file is there: https://github.com/OCA/server-auth/blob/14.0/requirements.txt and it says you can add it manually as well.

**Comment by SAMSA-IT** [comment]
Dear Pedro,
we moved the requirements.txt file directly in the root of the repository, "same level" as the apps, not in a sub folder. Then we were able to install the app in Odoo.sh. Do you think you could do the same here to prevent others from having the same issue when installing the App on Odoo.sh?
