### ISSUE TITLE
Changing password of users is not working

### ISSUE THREAD

**Issue by jjsanta97** [OCA/server-auth#450]
## Module
password_security

## Describe the bug
When I try to change the password of a user the next error appears: 

![Captura de pantalla de 2022-11-29 14-28-32](https://user-images.githubusercontent.com/13875210/204632327-8f39a3f8-d58f-4718-bbc8-cee228ed4cb2.png)

## To Reproduce
**Affected versions**: 13.0

1. Go to Settings
2. Users & Companies
3. Users
4. Select any user
5. Action
6. Change Password
7. Click New Password blank space

**Expected behavior**
Change to a new password without problems.

**Additional context**
The module was installed in a odoo.sh server.

**Comment by Corvan** [comment]
Have the same problem, did you find a solution yet?

Fixed it, with using the right version branch (15.0)
