### ISSUE TITLE
auth_saml: users report disconnections when using multiple tabs in the same browser

### ISSUE THREAD

**Issue by gurneyalex** [OCA/server-auth#458]
some users report repeated disconnections when using auth_saml and multiple browser tabs. It seems that the different tabs trigger reconnections independently and this is super harmful for the end users who get prompted to reauthenticate every few minutes. 

Seen on odoo 15.0

**Comment by vincent-hatakeyama** [comment]
The module is in production and no such issue was brought.

Do you have more details, like other modules installed?
