### ISSUE TITLE
Cannot find where to "create a new authentication provider in Odoo"

### ISSUE THREAD

**Issue by jcolley** [OCA/server-auth#543]
## Module
auth_oidc (or possibly just lack of clear documentation)

## Describe the bug
After installing the `auth_oidc` plugin, I cannot find anywhere in the UI to "create a new authentication provider in Odoo" as the documentation suggests. The documentation does not elaborate any further, making it impossible to know if the plugin is installed correctly or simply not loading without any error messages.

I have installed the `auth_saml` plugin and configured it without issues, but would rather use `auth_oidc` if I can get it configured.
The `auth_oidc` directory permissions and location are identical to the `auth_saml`.

## To Reproduce
Odoo & auth_oidc v16

1. Begin without knowing what to expect after installation, and only the provided documentation for context
2. After having successfully installed and configure the `auth_saml` plugin, download the auth_oidc plugin & unzip to the Odoo addons directory so that it's next to the `auth_saml` directory
3. Correct the directory permissions if needed so that the user account running the odoo server has access
4. Restart the Odoo server

**Expected behavior**
Some kind of UI option(s) to be displayed in the Settings UI somewhere, providing options to "create a new authentication provider in Odoo" as the documentation states.

**Additional context**
Odoo is running in a Docker container and all plugin dependencies have been added to a custom image based on the official Odoo image. No other image modifications.

**Comment by CRogos** [comment]
You need to go into the developer mode. Than you have a menu entry in the settings:

![image](https://github.com/OCA/server-auth/assets/1799080/9b9f7f2e-2daa-40f7-8958-0e720a04b3d7)
