### ISSUE TITLE
vault: Any user can export all vault

### ISSUE THREAD

**Issue by CarlosRoca13** [OCA/server-auth#549]
Right now, a user with read permissions can export the keys of a vault. The keys are encripted, but some of our customers are uneasy with this function and would like to limit it to some users.

It occurs to us that this button is only available to the owner of the vault. Another approach could be to add a new permission to export the keys.

We have opened this issue to see what you think @fkantelberg 

ping @pedrobaeza 

TT44749

**Comment by fkantelberg** [comment]
What do you mean with "keys of the vault"? Do you mean the master keys (key in vault.right)? These are encrypted with the private keys of the users which shouldn't be readable (even though encrypted) but those aren't part of the export.

Are you referring to customers who export the secrets of a vault with bad passwords?

Please be more specific here.

**Comment by CarlosRoca13** [comment]
Sorry, what I meant was the secrets. Our client does not want that the vault users see the button for exporting secrets. 

So we thought we could hide the button for users who are not the owner. Or include a new right to allow or disallow exporting/importing.

**Comment by fkantelberg** [comment]
I would prefer 2 res.groups with additional fields on res.config.settings:
```
group_vault_export = fields.Boolean("Export Vaults", implied_group="vault.group_vault_export")
group_vault_import = fields.Boolean("Import Vaults", implied_group="vault.group_vault_import")
```

**Comment by CarlosRoca13** [comment]
Ok! I take it. Do you preffer that I make the change?

**Comment by fkantelberg** [comment]
That would be great otherwise it'll take some days
