### ISSUE TITLE
OpenID Connect addon fails with 401 invalid_request

### ISSUE THREAD

**Issue by jakubgs** [OCA/server-auth#563]
## Module
I'm trying to get Keycloak OAuth to work using your OpenID Connect addon.

## Describe the bug
When I try to log in I get `401` error from Keycloak:
```json
{"error": "invalid_request"}
```
The Keycoak log shows:
```log
type=USER_INFO_REQUEST_ERROR, error=invalid_token, auth_method=validate_access_token, realmId=example-org, clientId=null, userId=null
```
I have narrowed it down to this section, specifically the `else` block is being run:
```python
    def _auth_oauth_rpc(self, endpoint, access_token):
        if self.env['ir.config_parameter'].sudo().get_param('auth_oauth.authorization_header'):
            response = requests.get(endpoint, headers={'Authorization': 'Bearer %s' % access_token}, timeout=10)
        else:
            response = requests.get(endpoint, params={'access_token': access_token}, timeout=10)
```
https://github.com/odoo/odoo/blob/50af40302c2849b99e8e501bc170cf887ca8e6fa/addons/auth_oauth/models/res_users.py#L27-L31

I commented out the `if` and `else` and ran the first version using `Authorization` header and it did work.

But what I don't get is why this code is running instead of your addon?

## To Reproduce
**Affected versions**: `16.0`
Configure Keycloak with this addon.

**Expected behavior**
I expected it to work.

**Additional context**
I installed `auth_oidc` from `2d9258349a912a0fed271ebaf2aed82a80dbaaca` commit of this repo.

**Comment by jakubgs** [comment]
I think this is related to this setting:

![image](https://github.com/OCA/server-auth/assets/2212681/76deb17d-8ba1-454b-93f0-c67ae98c7c0f)

But when I pick `OpenID Connect (authorization code flow)` I get this error in logs:
```
equests.exceptions.MissingSchema: Invalid URL 'False': No schema supplied. Perhaps you meant http://False?
```
Which I assume is due to missing `JWKS URL`, but I didn't think I needed that.

**Comment by jakubgs** [comment]
I identified there was a faulty `X-Forwarded-Proto: http` header which one of our proxies was sending. Fixing that to be `https` has resolved the error when using `OpenID Connect (authorization code flow)`.

But I had to set all URLs except for the `Data Endpoint` one:

![image](https://github.com/OCA/server-auth/assets/2212681/76197b34-af05-4e2e-88e7-1be602eb5e7c)

I also had to add `email:user_id` to `Token Map` field.

Hopefully this will help others with a similar issue.

**Comment by alebeta90** [comment]
Hi Jakubgs,

I got hit by an issue with this addon. When trying to log in using keycloak. It tells me `Invalid parameter: redirect_uri`

![image](https://github.com/OCA/server-auth/assets/11571266/d8da9e3d-a62b-4054-bd0d-4892231befff)

this is the same error you had?
