### ISSUE TITLE
vault: can't enter data? 

### ISSUE THREAD

**Issue by codeagencybe** [OCA/server-auth#568]
It seems I can't manually add secrets in a vault? I was just testing this module on runbot to see if and how it could be convenient for a potential project, but I'm stuck at a field that colors red with **** and I can't enter anything here. 
I also can't save the record because the field is blocking. 
I also don't see any popup or error or anything that indicates me why it's blocking me. 

## Module
vault

## Describe the bug
the "Value" field is not editable, can't click it, it colors red with no information or feedback why. 

## To Reproduce
**Affected versions**:
Only tested v15 so far. 

1. create a new vault (all good)
2. create a new secret in the vault
3. fill out the fields and you get blocked at the value field turning red
4. save function is also blocking because of this

**Expected behavior**
Accept my input

**Additional context**
Testing on runbot

![image](https://github.com/OCA/server-auth/assets/7568546/ac62ba27-34da-4411-a534-aff67bdc9e98)

**Comment by pedrobaeza** [comment]
You have to be in an HTTPS environment for working with this module. It's a requirement of browsers. Put https in the runboat URL.
