### ISSUE TITLE
vault: share complete entry?

### ISSUE THREAD

**Issue by codeagencybe** [OCA/server-auth#569]
There is no option to share the entire entry in a single share URL? 
If I need to share the login credentials for a website, I have to share 2 seperate lines, one for username, one for password. 
Or maybe I need to share also some extra PDF guide along the credentials, where files have no option to share at all. 
It's not really user friendly in this context. 

**Describe the solution you'd like**
add an action "share entry" that shares everything from that entry with the given user in an easy way. 

**Describe alternatives you've considered**
no alternatives possible afaik

Some example how 1Password works:
https://share.1password.com/s#NLWiqRUeyuR6a3PuL9igTbPvrdts455loF36YPNivg4

![image](https://github.com/OCA/server-auth/assets/7568546/605f7546-a457-4a19-a10f-7460fa1a58a8)

From a single click and URL I can have all the information I need to do the work I need to do.

**Comment by pedrobaeza** [comment]
Not possible for now.
