### ISSUE TITLE
Website quotation link for customers show login form

### ISSUE THREAD

**Issue by polimex-lgeorgiev** [OCA/server-auth#79]
When the customer open the link(Confirm & Sign) from email quotation, first time open Login form. Second click show the quotation. The problem is from auth_session_timeout. Exception URL (inactive_session_time_out_ignored_url) are configured for the path (/quote)
Odoo 11 CE

**Comment by pedrobaeza** [comment]
I don't get the problem, and you should put the module and the version you have the issue with in the title

**Comment by polimex-lgeorgiev** [comment]
Sorry
Module version 11.0.1.0.0 / Odoo 11.0-20190118 
To simulate problem get the link from the e-mail and open it in New Incognito browser tab
--
