### ISSUE TITLE
[11] auth_session_timeout Have to clear all cookies after logout

### ISSUE THREAD

**Issue by wilcobergacker** [OCA/server-auth#80]
Im using auth_session_timeout in combination with Odoo 11 EE and we regularly have an 50_x error "Service unavailable" when we're using Chrome.

The user is logged out properly, but after this  error we have to clear all cookies before we can login  in Odoo again. 

Any idea how to fix this?

**Comment by storagerepo** [comment]
Hi wilcobergacker,

I am also facing this issue,did you fix that issue?
