### ISSUE TITLE
[12] Password Security - Reset password

### ISSUE THREAD

**Issue by cuongnmtm** [OCA/server-auth#88]
Hi all,

I installed the password_security v12

When I:
1. Open user Form
2. Choose any user
3. Click Action & choose Change Password
4. An issue occurs when I try to click the text field to set the new password

> Error:
> TypeError: Value being assigned to HTMLMeterElement.value is not a finite floating-point value.
> 
> http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:3931
> Traceback:
> update@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:3931:1350
> _renderEdit/<@http://localhost:8069/web/content/326-6b41e4f/web.assets_backend.js:2673:1052
> then/</</<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:678
> fire@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:796:281
> add@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:797:467
> then/</<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:649
> each@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:625:758
> then/<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:553
> Deferred@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:803:189
> then@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:518
> _renderEdit@http://localhost:8069/web/content/326-6b41e4f/web.assets_backend.js:2673:1036
> OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:3538:485
> _render@http://localhost:8069/web/content/326-6b41e4f/web.assets_backend.js:1044:31
> start/<@http://localhost:8069/web/content/326-6b41e4f/web.assets_backend.js:1041:1516
> then/</</<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:678
> fire@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:796:281
> add@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:797:467
> then/</<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:649
> each@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:625:758
> then/<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:553
> Deferred@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:803:189
> then@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:518
> start@http://localhost:8069/web/content/326-6b41e4f/web.assets_backend.js:1041:1425
> OdooClass.extend/</prototype[name]</<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:3538:485
> _widgetRenderAndInsert/<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:3683:47
> then/</</<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:678
> fire@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:796:281
> fireWith@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:801:198
> updateFunc/<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:804:482
> fire@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:796:281
> fireWith@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:801:198
> then/</</<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:874
> fire@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:796:281
> fireWith@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:801:198
> Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:803:56
> rpc/<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:3588:436
> then/</</<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:678
> fire@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:796:281
> fireWith@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:801:198
> Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:803:56
> fire@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:796:281
> fireWith@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:801:198
> Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:803:56
> genericJsonRpc/<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:3557:1
> then/</</<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:678
> fire@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:796:281
> fireWith@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:801:198
> then/</</<@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:802:874
> fire@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:796:281
> fireWith@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:801:198
> done@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:1192:86
> callback@http://localhost:8069/web/content/325-0efc0a7/web.assets_common.js:1212:15

Thanks for your help

**Comment by pedrobaeza** [comment]
@shepilov-vladislav can you check this?

**Comment by shepilov-vladislav** [comment]
> @shepilov-vladislav can you check this?

@pedrobaeza This PR https://github.com/OCA/server-auth/pull/85 will fix this issue

**Comment by pedrobaeza** [comment]
OK, thanks

**Comment by phatminh** [comment]
Thanks !

**Comment by amkarthik** [comment]
> > @shepilov-vladislav can you check this?
> 
> @pedrobaeza This PR #85 will fix this issue

As said, PR #85 fixed this issue.
Thanks.

When we can expect it to be merged to 12.0?

**Comment by pedrobaeza** [comment]
That PR includes a lot of changes that are unrelated to fixing this, so it can't be simply accepted quickly. I would recommend to extract the bugfix to other PR for giving it more priority.

**Comment by amkarthik** [comment]
@pedrobaeza 
Extracted the fix from the PR https://github.com/OCA/server-auth/pull/85 and the seperate PR is https://github.com/OCA/server-auth/pull/121
Thanks
