### ISSUE TITLE
[11] Password Security - Disable history requires 1 not 0

### ISSUE THREAD

**Issue by samdohrey** [OCA/server-auth#89]
Hello,

We are hoping to install the Password security module but noticed a strange issue. We wish to disable the history check, as per the pop-up instructions "0 to disable". However this does not seem to work, we have to enter the value 1. This seems minor but could cause frustration to new users of the module

**Steps:**
In the password policy set (for ease of use):
Days = 0
Minimum Hours = 0
Characters = 0
**History = 0**
Lower = 1
Upper = 1
Numeric = 1
Special = 0

Ensure users can reset their own passwords
Create a new user, login and logout as said user
Using the Reset password mechanism on the login page
Set new password as Abcd1       Login
Set new password as Abcd1       Again. Login. User was able to use same password
Set new password as Abcd1       User sees error "Cannot use the most recent 0 passwords"

Login as a user with settings permissions and in password policy set History to 1.
Repeat the above test, the user can reuse the same password unlimited times

Expected:
On the third attempt the user can use the repeat password when history = 0

Kind regards,

Sam

**Comment by LuceEasyPme** [comment]
Thank you! It helped a lot!
Luce
